# LLM Configuration
llm:
  model_name: "gpt-4o-mini"
  temperature: 0.3
  timeout: 30

# Simulation Configuration
simulation:
  output_format: "json"
  save_detailed_logs: true
  batch_size: 10  # Number of concurrent requests
  
# File Paths
paths:
  persona_data_dir: "data"
  product_data_dir: "data/product_info"
  results_dir: "results"
  prompt_file: "prompt.yaml"

# Persona Configuration
persona:
  filename: "persona_99"  # Persona filename in data/ (.csv extension will be auto-added)

# Product Configuration
product:
  filename: "스팸"  # Product info filename in data/product_info/ (.json extension will be auto-added)

# OpenAI API Configuration
openai:
  api_base: "https://api.openai.com/v1"
  max_retries: 3
  retry_delay: 1

# Prompt Configuration
prompts:
  system_prompt: "system_prompt_A"  # Which system prompt to use from prompt.yaml
  user_prompt: "user_prompt_A"      # Which user prompt to use from prompt.yaml
