# LLM Configuration
llm:
  model_name: "gpt-4o-mini"
  temperature: 0.3
  timeout: 30

# Simulation Configuration
simulation:
  output_format: "json"
  save_detailed_logs: true
  batch_size: 20  # Number of concurrent requests
  
# File Paths
paths:
  persona_data_dir: "data"
  product_data_dir: "data/product_info"
  results_dir: "results2"
  prompt_file: "prompt.yaml"

# Persona Configuration
persona:
  # Type A: Uses CSV file from data/ directory
  filename: "persona"  # CSV filename in data/ (.csv extension will be auto-added) - Only used for Type A
  
  # Type B & C: Uses JSON file from persona/ directory
  # File path: persona/{product.filename}.json - Uses product filename automatically
  
  sample_size: 0  # Number of personas to randomly sample (0 = use all personas)

# Product Configuration
product:
  filename: "동원참치액_진"  # Product info filename in data/product_info/ (.json extension will be auto-added)

# OpenAI API Configuration
openai:
  api_base: "https://api.openai.com/v1"
  max_retries: 3
  retry_delay: 1

# Prompt Configuration
prompts:
  type: "D"  # Prompt type: "A" for single question, "B" for multi-question, "C" for conversion analysis, or "D" for TypeD product selection
